"""add payment_ref to entry

Revision ID: 73e5c3629918
Revises: 92f8339580ea
Create Date: 2019-05-11 22:07:52.305816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e5c3629918'
down_revision = '92f8339580ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('payment_reference', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'payment_reference')
    # ### end Alembic commands ###
