"""add an is_delete column to entries table

Revision ID: 92f8339580ea
Revises: 1ba895640e01
Create Date: 2018-06-14 18:48:08.562384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f8339580ea'
down_revision = '1ba895640e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'is_deleted')
    # ### end Alembic commands ###
